[package]
name = "slab_allocator_core"
version = "0.2.0"
authors = ["Andrew Warkentin <andreww591@gmail.com>", "Robert Węcławski <r.weclawski@gmail.com>"]
license = "MIT"

description = "Slab allocator for no_std systems. Uses multiple slabs with blocks of different sizes (including user-defined sizes). Supports dynamically growing and shrinking the heap. Needs a target-specific wrapper when used as a global allocator (the one provided by sel4-alloc is one example of such a wrapper)"
keywords = ["slab", "allocator", "no_std", "heap", "kernel"]

repository = "https://gitlab.com/uxrt/core-supervisor/fel4/slab_allocator_core"

[dependencies]
intrusive-collections = { version = "0.9", features = ["nightly"] }
sparse-array = { version = "0.2.0", path = "../rust-sparse-array", features = ["no_std"] }
custom-slab-allocator = { version = "0.1.0", path = "../custom-slab-allocator" }
log = { version = "0.4" }

[features]
debug = []
