# Copyright (c) 2018-2022 Andrew Warkentin
# 
# Based on code from Robigalia:
#
# Copyright (c) 2015 The Robigalia Project Developers
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# http://www.apache.org/licenses/LICENSE-2.0> or the MIT license <LICENSE-MIT
# or http://opensource.org/licenses/MIT>, at your option. All files in the
# project carrying such notice may not be copied, modified, or distributed
# except according to those terms.
[package]
name = "sel4"
version = "0.0.14"
authors = ["Andrew Warkentin <andreww591@gmail.com>"]
description = "High-level Rust interface to the seL4 kernel"
#documentation = "https://doc.robigalia.org/sel4"
repository = "https://gitlab.com/uxrt/core-supervisor/rust-sel4.git"
readme = "README.md"
license = "MIT OR Apache-2.0"

[features]
unstable = []

[build-dependencies]
selfe-config = { path = "../selfe-sys/selfe-config" }

[dependencies]
selfe-sys = { version = "0.1.2", path = "../selfe-sys" }
sel4-start = { path = "../selfe-sys/sel4-start", features = ["panic_handler"] }
