# Copyright (c) 2021 Andrew Warkentin
#
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# http://www.apache.org/licenses/LICENSE-2.0> or the MIT license <LICENSE-MIT
# or http://opensource.org/licenses/MIT>, at your option. All files in the
# project carrying such notice may not be copied, modified, or distributed
# except according to those terms.
#
[package]
name = "sel4-thread"
version = "0.1.0"
authors = ["Andrew Warkentin <andreww591@gmail.com>"]
description = "Thread library for seL4"
repository = "https://gitlab.com/uxrt/core-supervisor/fel4/sel4-thread"

[dependencies]
sel4 = { version = "0.0.14", path = "../rust-sel4" }
custom-slab-allocator = { version = "0.1.0", path = "../custom-slab-allocator" }
failure = { version = "0.1.5", features = ["failure_derive"], default-features = false }
log = { version = "0.4" }
selfe-sys = { version = "0.1.2", path = "../selfe-sys" }
sel4-thread-park = { version = "0.1.0", path = "../sel4-thread-park" }

[build-dependencies]
selfe-config = { path = "../selfe-sys/selfe-config" }

[dependencies.sel4-alloc]
features = []
path = "../sel4-alloc"

[features]
default = ["kobj_alloc"]
kobj_alloc = []
debug = []
